In [1]:
# Generate the video for the env with a trained model

In [2]:
import numpy as np
import gymnasium as gym
from stable_baselines3 import PPO, SAC, TD3
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.vec_env import VecFrameStack, DummyVecEnv, SubprocVecEnv

import torchdriveenv
from torchdriveenv.env_utils import load_waypoint_suite_data, load_rl_training_config

Commercial access denied and fallback to check for academic access.


In [3]:
model = SAC.load("models/BaselineAlgorithm.sac_1710579405/model")

/usr/local/lib/python3.8/dist-packages/stable_baselines3/common/buffers.py:241: UserWarning: This system does not have apparently enough memory to store the complete replay buffer 73.74GB > 44.94GB
  warnings.warn(


In [4]:
data = load_waypoint_suite_data("data/validation_cases.yml")
env_config = load_rl_training_config("env_configs/rl_training.yml").env
env_config.render_mode="video"

In [5]:
def make_env():
    env = gym.make('torchdriveenv-v0', args={'cfg': env_config, 'data': data})
    env = Monitor(env)  
    return env

In [6]:
def main(cfg, model):
    env = DummyVecEnv([make_env])
    env = VecFrameStack(env, n_stack=3, channels_order="first")
    obs = np.expand_dims(env.reset()[0], 0)
    states = None
    episode_starts = [True]

    while True:
        actions, states = model.predict(
         obs,  
         state=states,
         episode_start=episode_starts,
         deterministic=True,
        )
        obs, reward, done, info = env.step(actions)      
        if done:
            break
    env.close()

In [7]:
env_config

EnvConfig(ego_only=False, use_mock_lights=True, max_environment_steps=200, use_background_traffic=True, terminated_at_infraction=True, seed=None, simulator=TorchDriveConfig(renderer=RendererConfig(backend='default', render_agent_direction=True, left_handed_coordinates=True, highlight_ego_vehicle=True), single_agent_rendering=False, collision_metric=<CollisionMetric.nograd: 'nograd'>, offroad_threshold=0.5, left_handed_coordinates=True), render_mode='video', video_filename='rendered_video.mp4', video_res=1024, video_fov=200)

In [8]:
main(env_config, model)

INFO:torchdriveenv.gym_env:seed: 94339140
INFO:torchdriveenv.gym_env:    def get_reward(self):
        x = self.simulator.get_state()[..., 0]
        y = self.simulator.get_state()[..., 1]
        psi = self.simulator.get_state()[..., 2]

        d = math.dist((x, y), (self.last_x, self.last_y)) if (self.last_x is not None) and (self.last_y is not None) else 0
        distance_reward = 1 if d > 0.5 else 0
        psi_reward = (1 - math.cos(psi - self.last_psi)) * (-20.0) if (self.last_psi is not None) else 0
        if self.check_reach_target():
            reach_target_reward = 10
            self.reached_waypoint_num += 1
        else:
            reach_target_reward = 0
        r = torch.zeros_like(x)
        r += reach_target_reward + distance_reward + psi_reward
        return r

/usr/local/lib/python3.8/dist-packages/gymnasium/utils/passive_env_checker.py:135: UserWarning: WARN: The obs returned by the `reset()` method was expecting numpy array dtype to be uint8, actual type: flo

[[-0.9361826  0.2978707]]
[0.518107]
[[-0.8031012  -0.23261204]]
[0.72297275]
[[-0.90311414  0.00355896]]
[0.99993885]
[[-0.8710587   0.26287925]]
[0.717716]
[[ 0.57887185 -0.2554588 ]]
[0.71258056]
[[0.9218943  0.25320256]]
[0.68464726]
[[ 0.9126506  -0.10628325]]
[0.9355184]
[[ 0.91280055 -0.21907765]]
[10.707406]
[[0.25808787 0.25949073]]
[0.5854657]
[[ 0.26796222 -0.1321237 ]]
[0.88458645]
[[-0.9227927   0.04424387]]
[0.9880859]
[[0.93938994 0.19637099]]
[0.7493201]
[[ 0.9726107  -0.29192293]]
[0.4146078]
[[ 0.9453707  -0.22947367]]
[0.5928436]
[[ 0.9280665 -0.0873912]]
[0.9331261]
[[ 0.93786764 -0.13601865]]
[0.82592005]
[[0.94622254 0.00571206]]
[0.9996621]
[[ 0.9456763  -0.21824992]]
[0.49035373]
[[ 0.9078193  -0.29614994]]
[0.0298631]
[[ 0.87695193 -0.29972708]]
[-0.05863291]
[[-0.93622684 -0.26965562]]
[0.18815841]
[[-0.93814754  0.07524079]]
[0.93750125]
[[-0.95238864  0.29634172]]
[10.166854]
[[-0.51846343  0.2937168 ]]
[0.21481869]
[[-0.8817146  -0.27643192]]
[0.34914774]
[